#!/bin/bash
#NOTE: DO NOT EDIT THIS FILE-- MAY RESULT IN INCOMPLETE SUBMISSIONS
set -euo pipefail

# these notebooks should ideally
# be in order of questions so
# that the generated pdf is
# in order of questions
NOTEBOOKS=(
	"DDPM.ipynb"
)

CODE=(
	"dl/gaussian_diffusion.py"
	"dl/unet.py"
	"dl/ddpm_trainer.py"
	"dl/emoji_dataset.py"
)

PDF_FILENAME="a3_inline_submission.pdf"
ZIP_FILENAME="a3_code_submission.zip"

C_R="\e[31m"
C_G="\e[32m"
C_BLD="\e[1m"
C_E="\e[0m"

for FILE in "${NOTEBOOKS[@]}"
do
	if [ ! -f ${FILE} ]; then
		echo -e "${C_R}Required file ${FILE} not found, Exiting.${C_E}"
		exit 0
	fi
done

echo -e "### Creating PDF ###"
python makepdf.py --notebooks "${NOTEBOOKS[@]}" --pdf_filename "${PDF_FILENAME}"

echo -e "### Creating Code ZIP ###"
zip -q "${ZIP_FILENAME}" -r ${NOTEBOOKS[@]} $(find . -name '*.py' -not -name 'makepdf.py') "dl/saved" 2>/dev/null || zip -q "${ZIP_FILENAME}" -r ${NOTEBOOKS[@]} $(find . -name '*.py' -not -name 'makepdf.py')

echo -e "### Done! ###"
echo -e "Please submit the following THREE files to Lemida:"
echo -e "  1. ${C_BLD}${PDF_FILENAME}${C_E}"
echo -e "  2. ${C_BLD}${ZIP_FILENAME}${C_E}"
echo -e "  3. ${C_BLD}students.txt${C_E} (create this file manually with student names and IDs)"
